# Generated by Django 6.0.7 on 2026-09-04 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_host", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_auto_hide_threshold",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Report auto-hide threshold",
                    ),
                ),
                (
                    "trust_autopublish_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "New"),
                            (1, "Basic"),
                            (2, "Member"),
                            (3, "Regular"),
                            (4, "Leader"),
                        ],
                        null=True,
                        verbose_name="Auto-publish from trust level",
                    ),
                ),
                (
                    "spam_max_links",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Spam: max links per post"
                    ),
                ),
                (
                    "spam_banned_words",
                    models.TextField(blank=True, verbose_name="Spam: banned words"),
                ),
                (
                    "experts_min_trust_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "New"),
                            (1, "Basic"),
                            (2, "Member"),
                            (3, "Regular"),
                            (4, "Leader"),
                        ],
                        null=True,
                        verbose_name="Community experts: minimum trust level",
                    ),
                ),
                (
                    "badge_botanist_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Botanist badge: identifications shared",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum settings",
                "verbose_name_plural": "Forum settings",
            },
        ),
    ]
