# Generated by Django 6.0.5 on 2026-06-07 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("bio", models.TextField(blank=True)),
                ("signature", models.CharField(blank=True, max_length=255)),
                (
                    "trust_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Basic"),
                            (2, "Member"),
                            (3, "Regular"),
                            (4, "Leader"),
                        ],
                        default=0,
                    ),
                ),
                ("post_count", models.PositiveIntegerField(default=0)),
                ("flags_received", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wagtail_forum_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
