# Generated by Django 6.0.5 on 2026-06-07 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0006_spamchecktask"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["topic", "created_at"], name="wagtail_for_topic_i_cef904_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["board", "-last_post_at"], name="wagtail_for_board_i_38d417_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_opening_post", True)),
                fields=("topic",),
                name="uniq_opening_post_per_topic",
            ),
        ),
    ]
