# Generated by Django 6.0.5 on 2026-06-11 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0007_post_wagtail_for_topic_i_cef904_idx_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                condition=models.Q(("live", True)),
                fields=["updated_at", "id"],
                name="wf_topic_sync_idx",
            ),
        ),
    ]
