# Generated by Django 6.0.7 on 2026-07-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_author_subscriptions(apps, schema_editor):
    """Preserve today's behavior for existing topics (todo 253 slice 3): the
    pre-slice-3 fan-out always notified a topic's original author, unconditionally.
    Once fan-out becomes subscription-driven, an un-backfilled topic would
    silently stop notifying its author on the next reply — a regression on
    live data. Author-only, deliberately NOT past repliers: they were never
    notified before this slice, so retroactively subscribing them would
    surprise-spam a long-gone participant on a "necro-reply" to an old
    thread. Past repliers are covered going forward by auto-subscribe-on-reply.
    """
    Topic = apps.get_model("wagtail_forum", "Topic")
    TopicSubscription = apps.get_model("wagtail_forum", "TopicSubscription")
    TopicSubscription.objects.bulk_create(
        [
            TopicSubscription(user_id=author_id, topic_id=topic_id)
            for topic_id, author_id in Topic.objects.filter(
                author__isnull=False
            ).values_list("id", "author_id")
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0013_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="wagtail_forum.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_topic_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["topic"], name="wagtail_for_topic_i_b797ef_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "topic"), name="uniq_topic_subscription"
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_author_subscriptions, migrations.RunPython.noop),
    ]
