# Generated by Django 6.0.7 on 2026-07-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0014_topicsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[("reply", "Reply"), ("mention", "Mention")], max_length=20
            ),
        ),
    ]
