# Generated by Django 6.0.7 on 2026-07-30 03:08

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtail_forum", "0016_topicread"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
