# Generated by Django 6.0.7 on 2026-07-31 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0017_topic_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="solved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="solved_post",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtail_forum.post",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("reply", "Reply"),
                    ("mention", "Mention"),
                    ("solution", "Answer accepted"),
                ],
                max_length=20,
            ),
        ),
    ]
