# Generated by Django 6.0.7 on 2026-07-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0018_topic_solved_at_topic_solved_post_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumIdentificationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("candidates", models.JSONField(blank=True, default=list)),
                (
                    "identification_result_id",
                    models.CharField(blank=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identification",
                        to="wagtail_forum.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum identification attachment",
            },
        ),
    ]
