# Generated by Django 6.0.7 on 2026-08-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0019_forumidentificationattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumprofile",
            name="title",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
