# Generated by Django 6.0.7 on 2026-08-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0021_topicbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumindex",
            name="featured_description",
            field=models.TextField(
                blank=True,
                help_text="Hero description shown under the featured topic's own title.",
            ),
        ),
        migrations.AddField(
            model_name="forumindex",
            name="featured_eyebrow",
            field=models.CharField(
                blank=True, default="Community event", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="forumindex",
            name="featured_topic",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Feature this topic as the landing page's 'Community "
                    "event' hero. Leave blank for the evergreen hero."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtail_forum.topic",
            ),
        ),
    ]
