# Generated by Django 6.0.7 on 2026-08-29 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0023_forumactivitydate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_blocks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_blocks_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["blocked"], name="wagtail_for_blocked_af1cfa_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="uniq_forum_block"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker", models.F("blocked")), _negated=True
                        ),
                        name="forum_block_not_self",
                    ),
                ],
            },
        ),
    ]
