# Generated by Django 6.0.7 on 2026-09-05 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # Forward is data-safe: every row that satisfied the old (poll, user)
    # uniqueness satisfies (poll, user, option). Reversing is NOT once a
    # multi-choice poll has a voter with 2+ rows — re-adding uniq_poll_vote
    # would fail on those rows. Roll back by deleting multi-choice ballots
    # first, or don't (todo 349 review note).

    dependencies = [
        ("wagtail_forum", "0027_alter_topic_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pollvote",
            name="uniq_poll_vote",
        ),
        migrations.AddField(
            model_name="poll",
            name="max_choices",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="pollvote",
            constraint=models.UniqueConstraint(
                fields=("poll", "user", "option"), name="uniq_poll_vote_option"
            ),
        ),
    ]
