# Generated by Django 6.0.7 on 2026-09-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0028_poll_max_choices_and_multi_vote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "muted",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_mutes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "muter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_mutes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["muted"], name="wagtail_for_muted_i_582fcb_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("muter", "muted"), name="uniq_forum_mute"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("muter", models.F("muted")), _negated=True),
                        name="forum_mute_not_self",
                    ),
                ],
            },
        ),
    ]
