# Generated by Django 6.0.7 on 2026-09-05 07:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0030_badges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("quote", 2),
                    ("code", 5),
                    ("image", 6),
                    ("embed", 7),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "max_length": 200},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul", "code"]},
                    ),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {},
                    ),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    7: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "A video URL from a provider the site allows"},
                    ),
                },
            ),
        ),
    ]
