# Generated by Django 6.0.7 on 2026-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0034_post_quote_and_quote_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumprofile",
            name="notification_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
