# Generated by Django 6.0.7 on 2026-09-05 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Rows per bulk_create in the backfill — bounded memory on a large DM table.
BACKFILL_BATCH_SIZE = 500


def backfill_participants(apps, schema_editor):
    """Every existing (direct) conversation gets one participant row per
    side, carrying that side's read marker — no data loss (todo 350)."""
    Conversation = apps.get_model("wagtail_forum", "Conversation")
    Participant = apps.get_model("wagtail_forum", "ConversationParticipant")
    rows = []
    for conv in Conversation.objects.all().iterator():
        rows.append(
            Participant(
                conversation_id=conv.pk,
                user_id=conv.participant_a_id,
                joined_at=conv.created_at,
                read_at=conv.participant_a_read_at,
            )
        )
        rows.append(
            Participant(
                conversation_id=conv.pk,
                user_id=conv.participant_b_id,
                joined_at=conv.created_at,
                read_at=conv.participant_b_read_at,
            )
        )
        if len(rows) >= BACKFILL_BATCH_SIZE:
            Participant.objects.bulk_create(rows, ignore_conflicts=True)
            rows = []
    if rows:
        Participant.objects.bulk_create(rows, ignore_conflicts=True)


def restore_read_columns(apps, schema_editor):
    """Reverse: copy the read markers back onto the pair columns for direct
    conversations (group rows have no column to receive them)."""
    Conversation = apps.get_model("wagtail_forum", "Conversation")
    Participant = apps.get_model("wagtail_forum", "ConversationParticipant")
    # Groups have no pair columns to fall back to; the schema below this
    # migration cannot hold them, so a downgrade discards them (documented
    # dev-only limitation) rather than failing on the NOT NULL reversal.
    Conversation.objects.filter(kind="group").delete()
    for conv in Conversation.objects.filter(kind="direct").iterator():
        marks = dict(
            Participant.objects.filter(conversation_id=conv.pk).values_list(
                "user_id", "read_at"
            )
        )
        Conversation.objects.filter(pk=conv.pk).update(
            participant_a_read_at=marks.get(conv.participant_a_id),
            participant_b_read_at=marks.get(conv.participant_b_id),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0035_notification_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["joined_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_conversations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[("direct", "Direct"), ("group", "Group")],
                default="direct",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="participant_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_conversations_as_a",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="participant_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_conversations_as_b",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "direct"),
                        ("participant_a__isnull", False),
                        ("participant_b__isnull", False),
                    ),
                    models.Q(
                        ("kind", "group"),
                        ("participant_a__isnull", True),
                        ("participant_b__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="forum_conversation_kind_shape",
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="wagtail_forum.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_conversation_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["user", "conversation"], name="wagtail_for_user_id_c3f471_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationparticipant",
            constraint=models.UniqueConstraint(
                fields=("conversation", "user"), name="uniq_forum_conversation_member"
            ),
        ),
        migrations.RunPython(backfill_participants, restore_read_columns),
        migrations.RemoveField(
            model_name="conversation",
            name="participant_a_read_at",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="participant_b_read_at",
        ),
    ]
