# Generated by Django 6.1.1 on 2026-09-07 18:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_forum", "0036_group_conversations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("quote", 2),
                    ("post_quote", 5),
                    ("code", 7),
                    ("image", 8),
                    ("embed", 9),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "max_length": 200},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul", "code"]},
                    ),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: ("wagtail.blocks.IntegerBlock", (), {"min_value": 1}),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: ("wagtail.blocks.StructBlock", [[("post", 3), ("text", 4)]], {}),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 6), ("code", 4)]],
                        {},
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "A video URL from a provider the site allows"},
                    ),
                },
            ),
        ),
    ]
