# Generated by Django 6.1.1 on 2026-09-26 02:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_forum", "0038_normalise_forum_image_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("quote", 2),
                    ("post_quote", 5),
                    ("code", 7),
                    ("image", 8),
                    ("embed", 9),
                    ("link_preview", 16),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "max_length": 200},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul", "code"]},
                    ),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: ("wagtail.blocks.IntegerBlock", (), {"min_value": 1}),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: ("wagtail.blocks.StructBlock", [[("post", 3), ("text", 4)]], {}),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 6), ("code", 4)]],
                        {},
                    ),
                    8: ("wagtail.images.blocks.ImageBlock", [], {}),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "A video URL from a provider the site allows"},
                    ),
                    10: ("wagtail.blocks.URLBlock", (), {"max_length": 2048}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 500, "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 253, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 10),
                                ("title", 11),
                                ("description", 12),
                                ("image", 13),
                                ("site_name", 14),
                                ("domain", 15),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
