[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Start permissive
check_untyped_defs = true
no_implicit_optional = true
ignore_missing_imports = true

# Strict checking for service layer
[[tool.mypy.overrides]]
module = "apps.plant_identification.services.*"
disallow_untyped_defs = false  # Permissive for now, some services still need work
warn_unreachable = true
strict_optional = true

# Django-specific overrides
[[tool.mypy.overrides]]
module = "apps.plant_identification.models"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "backend.settings"
