# Generated by Django 5.2.4 on 2025-08-19 19:22

from django.db import migrations


def migrate_care_guides_to_blog(apps, schema_editor):
    """No-op. Historically ran the migrate_care_guides_to_blog command on every
    migrate, which could auto-create a superuser with a hardcoded password on a
    production deploy. The one-time content migration has long since run; run the
    management command manually if it is ever needed again."""


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpostpage_content_blocks"),
        ("plant_identification", "0005_alter_plantspeciespage_plant_species"),
    ]

    operations = [
        migrations.RunPython(
            migrate_care_guides_to_blog,
            migrations.RunPython.noop,
        ),
    ]
