# Generated by Django 5.2.7 on 2025-10-24 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250819_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the viewer', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=255)),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL (where the user came from)')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When the post was viewed')),
                ('post', models.ForeignKey(help_text='The blog post that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.blogpostpage')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the post (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post View',
                'verbose_name_plural': 'Blog Post Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', '-viewed_at'], name='blog_blogpo_post_id_852bb5_idx'), models.Index(fields=['-viewed_at'], name='blog_blogpo_viewed__029e7b_idx'), models.Index(fields=['user', '-viewed_at'], name='blog_blogpo_user_id_47e976_idx')],
            },
        ),
    ]
