# Generated by Django 6.1.1 on 2026-09-24 20:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_add_blog_title_trigram_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="content_blocks",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("quote", 4),
                    ("code", 7),
                    ("plant_spotlight", 15),
                    ("call_to_action", 20),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Add a heading to structure your content",
                            "icon": "title",
                            "template": "blog/blocks/heading.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add paragraph text with AI assistance for plant content",
                            "icon": "pilcrow",
                            "template": "blog/blocks/paragraph.html",
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Who said this quote?", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("quote_text", 2), ("attribution", 3)]],
                        {"icon": "openquote", "template": "blog/blocks/quote.html"},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("bash", "Bash"),
                                ("json", "JSON"),
                            ],
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.TextBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 5), ("code", 6)]],
                        {"icon": "code", "template": "blog/blocks/code.html"},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "🌱 Enter plant name - auto-population will fill other fields"
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Scientific name (auto-populated from plant database)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Plant description (auto-populated from database or AI-generated)"
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("easy", "Easy"),
                                ("moderate", "Moderate"),
                                ("difficult", "Difficult"),
                            ],
                            "help_text": "Care difficulty level (auto-calculated from plant requirements)",
                        },
                    ),
                    12: (
                        "apps.blog.blocks.APIImageChooserBlock",
                        (),
                        {
                            "help_text": "Plant image (suggestions provided from database)",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Photo credit shown under the image, e.g. "Photo by Jane Doe on Unsplash"',
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link for the photo credit (photographer or source page)",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("plant_name", 8),
                                ("scientific_name", 9),
                                ("description", 10),
                                ("care_difficulty", 11),
                                ("image", 12),
                                ("image_credit", 13),
                                ("image_credit_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Spotlight a specific plant with auto-populated data from our plant database",
                            "icon": "snippet",
                            "template": "blog/blocks/plant_spotlight.html",
                        },
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {}),
                    17: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    18: ("wagtail.blocks.URLBlock", (), {}),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ]
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("cta_title", 16),
                                ("cta_description", 17),
                                ("button_text", 16),
                                ("button_url", 18),
                                ("button_style", 19),
                            ]
                        ],
                        {"icon": "link", "template": "blog/blocks/call_to_action.html"},
                    ),
                },
                help_text="Main content blocks with AI assistance for plant-related content",
            ),
        ),
    ]
