# Generated by Django 6.1.1 on 2026-10-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_plant_spotlight_image_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="blognewsletter",
            name="confirmation_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last confirmation email; links from earlier ones stop working",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blognewsletter",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the address confirmed by email link",
                null=True,
            ),
        ),
    ]
