# Generated by Django 5.2.5 on 2025-08-23 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_care_reminder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprogress',
            name='batch_identification_tried',
            field=models.BooleanField(default=False, help_text='User tried batch identification feature'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='completed_checklist',
            field=models.BooleanField(default=False, help_text='User completed the getting started checklist'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='completed_first_tour',
            field=models.BooleanField(default=False, help_text='User completed their first guided tour'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='completed_tours',
            field=models.JSONField(default=list, help_text="List of completed tour identifiers (e.g., 'dashboard')"),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='completed_welcome',
            field=models.BooleanField(default=False, help_text='User completed welcome step'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='demo_data_created',
            field=models.BooleanField(default=False, help_text='Demo data has been generated for this user'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='demo_data_skipped',
            field=models.BooleanField(default=False, help_text='User chose to skip creating demo data'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='first_care_reminder_created',
            field=models.BooleanField(default=False, help_text='User created their first care reminder'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='first_forum_post_created',
            field=models.BooleanField(default=False, help_text='User created their first forum post'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='first_identification_completed',
            field=models.BooleanField(default=False, help_text='User completed their first plant identification'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False, help_text='User enabled push notifications during onboarding'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_level_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time trust level was recalculated', null=True),
        ),
    ]
