# Generated by Django 5.2.5 on 2025-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_onboardingprogress_batch_identification_tried_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hardiness_zone',
            field=models.CharField(blank=True, help_text="USDA Hardiness Zone (e.g., '7a', '9b') for climate-specific recommendations", max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for precise location-based features', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_privacy',
            field=models.CharField(choices=[('private', "Private - Don't share my location"), ('zone_only', 'Zone Only - Share my hardiness zone'), ('city', 'City Level - Share my city/region'), ('precise', 'Precise - Share exact coordinates (for close friends)')], default='zone_only', help_text='Control how much location information is shared with other users', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for precise location-based features', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='microclimate_offset',
            field=models.SmallIntegerField(default=0, help_text='Temperature offset in Fahrenheit for microclimate adjustments (-10 to +10)'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code for weather and local event integration', max_length=10),
        ),
    ]
