# Generated by Django 6.0.5 on 2026-05-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_email_alter_user_trust_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Firebase Authentication UID bound to this account",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
