# Generated by Django 6.0.7 on 2026-07-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_firebase_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(
                default=False,
                help_text="Premium entitlement gating AI features (thread summaries, etc.)",
            ),
        ),
    ]
