# Generated by Django 6.1.1 on 2026-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_backfill_verified_email_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_emails_sent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Verification mails queued in the current window (capped)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_window_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current verification-mail window began",
                null=True,
            ),
        ),
    ]
