# Generated by Django 6.1.1 on 2026-09-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_lowercase_email_addresses"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="carereminder",
            name="users_carer_user_id_277b2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminder",
            name="users_carer_next_re_2b563a_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminder",
            name="users_carer_reminde_64b263_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminderlog",
            name="users_carer_reminde_09dc02_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminderlog",
            name="users_carer_action_50409b_idx",
        ),
        migrations.RemoveField(
            model_name="onboardingprogress",
            name="first_care_reminder_created",
        ),
        migrations.RemoveField(
            model_name="user",
            name="care_reminder_email",
        ),
        migrations.RemoveField(
            model_name="carereminderlog",
            name="reminder",
        ),
        migrations.DeleteModel(
            name="CareReminder",
        ),
        migrations.DeleteModel(
            name="CareReminderLog",
        ),
    ]
