# Generated by Django 6.1.1 on 2026-09-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_lowercase_email_addresses"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="carereminder",
            name="users_carer_user_id_277b2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminder",
            name="users_carer_next_re_2b563a_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminder",
            name="users_carer_reminde_64b263_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminderlog",
            name="users_carer_reminde_09dc02_idx",
        ),
        migrations.RemoveIndex(
            model_name="carereminderlog",
            name="users_carer_action_50409b_idx",
        ),
        # Expand/contract (PR #854 review): the old container keeps serving
        # while this migration runs, and it SELECTs these columns on every
        # User / OnboardingProgress fetch. So this deploy gives each column a
        # DB default (new code inserts without it) and removes it from Django
        # state only; a later migration drops the columns (todo 458).
        migrations.AlterField(
            model_name="onboardingprogress",
            name="first_care_reminder_created",
            field=models.BooleanField(
                default=False,
                db_default=False,
                help_text="User created their first care reminder",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="onboardingprogress",
                    name="first_care_reminder_created",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="care_reminder_email",
            field=models.BooleanField(
                default=False,
                db_default=False,
                help_text="Receive email notifications for plant care reminders",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="user",
                    name="care_reminder_email",
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="carereminderlog",
            name="reminder",
        ),
        migrations.DeleteModel(
            name="CareReminder",
        ),
        migrations.DeleteModel(
            name="CareReminderLog",
        ),
    ]
