# Generated by Django 6.1.1 on 2026-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_delete_care_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demodata",
            name="target_onboarding_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("account_created", "Account Created"),
                    ("profile_completed", "Profile Completed"),
                    ("first_plant_identified", "First Plant Identified"),
                    ("care_card_saved", "Care Card Saved"),
                    ("forum_category_followed", "Forum Category Followed"),
                    ("first_forum_post", "First Forum Post Created"),
                    ("push_notifications_enabled", "Push Notifications Enabled"),
                    ("onboarding_completed", "Onboarding Completed"),
                ],
                help_text="Which onboarding step this demo data is relevant for",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingprogress",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("account_created", "Account Created"),
                    ("profile_completed", "Profile Completed"),
                    ("first_plant_identified", "First Plant Identified"),
                    ("care_card_saved", "Care Card Saved"),
                    ("forum_category_followed", "Forum Category Followed"),
                    ("first_forum_post", "First Forum Post Created"),
                    ("push_notifications_enabled", "Push Notifications Enabled"),
                    ("onboarding_completed", "Onboarding Completed"),
                ],
                default="account_created",
                help_text="Current step in the onboarding process",
                max_length=30,
            ),
        ),
    ]
