# Generated by Django 6.1.1 on 2026-10-09 15:30

from django.db import migrations, models

RETIRED_STEP = "care_reminder_set"
# The step that followed it before 0016 removed it.
NEXT_STEP = "onboarding_completed"


def remap_retired_onboarding_step(apps, schema_editor):
    """0016 only altered the choices, so a row may still hold the retired
    step (todo 458 item 8). Move it on and drop it from ``completed_steps``,
    which ``completion_percentage`` counts against the current step list."""
    OnboardingProgress = apps.get_model("users", "OnboardingProgress")
    OnboardingProgress.objects.filter(current_step=RETIRED_STEP).update(
        current_step=NEXT_STEP
    )
    # Filtered in Python: SQLite has no JSONField ``contains`` lookup.
    for progress in OnboardingProgress.objects.only("completed_steps"):
        if RETIRED_STEP not in progress.completed_steps:
            continue
        progress.completed_steps = [
            step for step in progress.completed_steps if step != RETIRED_STEP
        ]
        progress.save(update_fields=["completed_steps"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_drop_care_reminder_onboarding_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demodata",
            name="demo_type",
            field=models.CharField(
                choices=[
                    ("plant_species", "Sample Plant Species"),
                    ("identification_request", "Sample Identification Request"),
                    ("care_instructions", "Sample Care Instructions"),
                    ("forum_topic", "Sample Forum Topic"),
                    ("forum_post", "Sample Forum Post"),
                    ("user_plant", "Sample User Plant Collection"),
                ],
                help_text="Type of demo data this represents",
                max_length=30,
            ),
        ),
        # Contract half of 0015's expand/contract (todo 458). 0015 removed
        # both fields from Django state and left the columns, with a DB
        # default, for the old container to read during the rolling deploy.
        # Every container now runs code that never selects them, so they go.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE auth_user DROP COLUMN care_reminder_email",
                    reverse_sql=(
                        "ALTER TABLE auth_user ADD COLUMN care_reminder_email "
                        "boolean NOT NULL DEFAULT false"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE users_onboardingprogress "
                        "DROP COLUMN first_care_reminder_created"
                    ),
                    reverse_sql=(
                        "ALTER TABLE users_onboardingprogress "
                        "ADD COLUMN first_care_reminder_created "
                        "boolean NOT NULL DEFAULT false"
                    ),
                ),
            ],
        ),
        migrations.RunPython(remap_retired_onboarding_step, migrations.RunPython.noop),
    ]
