# Generated by Django 6.1.1 on 2026-10-10 02:55

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the unused ``DemoData`` model and its table (todo 532).

    Nothing creates or reads it, so the owner chose one migration over an
    expand/contract pair (2026-10-10). One exposure remains while the old
    container serves after ``migrate``: ``DemoData.created_by`` was
    ``SET_NULL``, so the old code's ``User.delete()`` issues an UPDATE on
    ``users_demodata`` and fails (rolled back) until cutover. See
    ``docs/rules/database.md`` on dropped tables and Python-side cascades.
    """

    dependencies = [
        ("users", "0017_drop_care_reminder_columns"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="demodata",
            name="users_demod_demo_ty_12e2e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="demodata",
            name="users_demod_target__89992b_idx",
        ),
        migrations.RemoveIndex(
            model_name="demodata",
            name="users_demod_is_feat_98f624_idx",
        ),
        migrations.DeleteModel(
            name="DemoData",
        ),
    ]
