# Generated by Django 6.1.1 on 2026-09-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_drop_garden_tables"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="plantcarereminder",
            name="core_plantc_user_id_a28d0f_idx",
        ),
        migrations.RemoveIndex(
            model_name="plantcarereminder",
            name="core_plantc_next_re_c88157_idx",
        ),
        migrations.RemoveIndex(
            model_name="plantcarereminder",
            name="core_plantc_care_ty_e61e0c_idx",
        ),
        migrations.DeleteModel(
            name="PlantCareReminder",
        ),
    ]
