# Generated by Django 5.2.4 on 2025-08-05 21:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0011_auto_20190627_2132'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAnnouncementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content_blocks', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('forum_announcement', 6), ('forum_rules', 7), ('moderator_info', 9), ('image', 10), ('call_to_action', 13), ('statistics', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'forum_integration/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'forum_integration/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 5: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('content', 3), ('is_pinned', 4), ('show_until', 5)]], {'icon': 'warning', 'template': 'forum_integration/blocks/announcement.html'}), 7: ('wagtail.blocks.StructBlock', [[('rule_title', 2), ('rule_description', 3)]], {'icon': 'list-ul', 'template': 'forum_integration/blocks/rules.html'}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('moderator_name', 2), ('moderator_bio', 3), ('contact_info', 8)]], {'icon': 'user', 'template': 'forum_integration/blocks/moderator.html'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'forum_integration/blocks/image.html'}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('button_text', 2), ('button_url', 11), ('description', 12)]], {'icon': 'link', 'template': 'forum_integration/blocks/cta.html'}), 14: ('wagtail.blocks.StructBlock', [[('stat_label', 2), ('stat_value', 2), ('stat_description', 12)]], {'icon': 'view', 'template': 'forum_integration/blocks/statistics.html'})}, help_text='Add content blocks for this forum page. Note: Nested blocks are not allowed.')),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('show_breadcrumbs', models.BooleanField(default=True, help_text='Show breadcrumb navigation')),
                ('enable_social_sharing', models.BooleanField(default=True, help_text='Enable social media sharing buttons')),
                ('is_pinned', models.BooleanField(default=True, help_text='Pin this announcement to the top of forum listings')),
                ('show_until', models.DateTimeField(blank=True, help_text='Hide this announcement after this date (optional)', null=True)),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance')], default='info', help_text='Type of announcement affects styling', max_length=20)),
                ('show_to_all', models.BooleanField(default=True, help_text='Show to all users, including guests')),
                ('show_to_members_only', models.BooleanField(default=False, help_text='Show only to registered members')),
            ],
            options={
                'verbose_name': 'Forum Announcement Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ForumCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content_blocks', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('forum_announcement', 6), ('forum_rules', 7), ('moderator_info', 9), ('image', 10), ('call_to_action', 13), ('statistics', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'forum_integration/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'forum_integration/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 5: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('content', 3), ('is_pinned', 4), ('show_until', 5)]], {'icon': 'warning', 'template': 'forum_integration/blocks/announcement.html'}), 7: ('wagtail.blocks.StructBlock', [[('rule_title', 2), ('rule_description', 3)]], {'icon': 'list-ul', 'template': 'forum_integration/blocks/rules.html'}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('moderator_name', 2), ('moderator_bio', 3), ('contact_info', 8)]], {'icon': 'user', 'template': 'forum_integration/blocks/moderator.html'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'forum_integration/blocks/image.html'}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('button_text', 2), ('button_url', 11), ('description', 12)]], {'icon': 'link', 'template': 'forum_integration/blocks/cta.html'}), 14: ('wagtail.blocks.StructBlock', [[('stat_label', 2), ('stat_value', 2), ('stat_description', 12)]], {'icon': 'view', 'template': 'forum_integration/blocks/statistics.html'})}, help_text='Add content blocks for this forum page. Note: Nested blocks are not allowed.')),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('show_breadcrumbs', models.BooleanField(default=True, help_text='Show breadcrumb navigation')),
                ('enable_social_sharing', models.BooleanField(default=True, help_text='Enable social media sharing buttons')),
                ('machina_forum_id', models.IntegerField(help_text='ID of the Django Machina forum this page represents')),
                ('topics_per_page', models.IntegerField(default=25, help_text='Number of topics to display per page')),
                ('allow_new_topics', models.BooleanField(default=True, help_text='Allow users to create new topics in this forum')),
                ('show_topic_stats', models.BooleanField(default=True, help_text='Show topic statistics (replies, views, etc.)')),
                ('require_approval', models.BooleanField(default=False, help_text='Require moderator approval for new topics')),
            ],
            options={
                'verbose_name': 'Forum Category Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ForumIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content_blocks', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('forum_announcement', 6), ('forum_rules', 7), ('moderator_info', 9), ('image', 10), ('call_to_action', 13), ('statistics', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'forum_integration/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'forum_integration/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 5: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('content', 3), ('is_pinned', 4), ('show_until', 5)]], {'icon': 'warning', 'template': 'forum_integration/blocks/announcement.html'}), 7: ('wagtail.blocks.StructBlock', [[('rule_title', 2), ('rule_description', 3)]], {'icon': 'list-ul', 'template': 'forum_integration/blocks/rules.html'}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('moderator_name', 2), ('moderator_bio', 3), ('contact_info', 8)]], {'icon': 'user', 'template': 'forum_integration/blocks/moderator.html'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'forum_integration/blocks/image.html'}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('button_text', 2), ('button_url', 11), ('description', 12)]], {'icon': 'link', 'template': 'forum_integration/blocks/cta.html'}), 14: ('wagtail.blocks.StructBlock', [[('stat_label', 2), ('stat_value', 2), ('stat_description', 12)]], {'icon': 'view', 'template': 'forum_integration/blocks/statistics.html'})}, help_text='Add content blocks for this forum page. Note: Nested blocks are not allowed.')),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('show_breadcrumbs', models.BooleanField(default=True, help_text='Show breadcrumb navigation')),
                ('enable_social_sharing', models.BooleanField(default=True, help_text='Enable social media sharing buttons')),
                ('forums_per_page', models.IntegerField(default=20, help_text='Number of forums to display per page')),
                ('show_statistics', models.BooleanField(default=True, help_text='Show forum statistics (total posts, topics, etc.)')),
                ('welcome_message', models.TextField(blank=True, help_text='Welcome message displayed at the top of the forum')),
            ],
            options={
                'verbose_name': 'Forum Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ForumModerationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content_blocks', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('forum_announcement', 6), ('forum_rules', 7), ('moderator_info', 9), ('image', 10), ('call_to_action', 13), ('statistics', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'forum_integration/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'forum_integration/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 5: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('content', 3), ('is_pinned', 4), ('show_until', 5)]], {'icon': 'warning', 'template': 'forum_integration/blocks/announcement.html'}), 7: ('wagtail.blocks.StructBlock', [[('rule_title', 2), ('rule_description', 3)]], {'icon': 'list-ul', 'template': 'forum_integration/blocks/rules.html'}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('moderator_name', 2), ('moderator_bio', 3), ('contact_info', 8)]], {'icon': 'user', 'template': 'forum_integration/blocks/moderator.html'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'forum_integration/blocks/image.html'}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('button_text', 2), ('button_url', 11), ('description', 12)]], {'icon': 'link', 'template': 'forum_integration/blocks/cta.html'}), 14: ('wagtail.blocks.StructBlock', [[('stat_label', 2), ('stat_value', 2), ('stat_description', 12)]], {'icon': 'view', 'template': 'forum_integration/blocks/statistics.html'})}, help_text='Add content blocks for this forum page. Note: Nested blocks are not allowed.')),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('show_breadcrumbs', models.BooleanField(default=True, help_text='Show breadcrumb navigation')),
                ('enable_social_sharing', models.BooleanField(default=True, help_text='Enable social media sharing buttons')),
                ('show_pending_posts', models.BooleanField(default=True, help_text='Show pending posts awaiting approval')),
                ('show_reported_content', models.BooleanField(default=True, help_text='Show reported posts and topics')),
                ('show_user_management', models.BooleanField(default=True, help_text='Show user management tools')),
                ('enable_spam_detection', models.BooleanField(default=True, help_text='Enable automatic spam detection')),
                ('auto_approve_trusted_users', models.BooleanField(default=True, help_text='Automatically approve posts from trusted users')),
            ],
            options={
                'verbose_name': 'Forum Moderation Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ForumPageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this mapping currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machina_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagtail_pages', to='forum.forum')),
                ('wagtail_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_mapping', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Forum Page Mapping',
                'verbose_name_plural': 'Forum Page Mappings',
                'unique_together': {('wagtail_page', 'machina_forum')},
            },
        ),
    ]
