# Generated by Django 5.2.4 on 2025-08-12 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0013_auto_20201220_1745'),
        ('forum_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=50)),
                ('prompt_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('action_type', models.CharField(choices=[('create', 'Create New Content'), ('enhance', 'Enhance Existing'), ('correct', 'Grammar/Style Correction'), ('continue', 'Continue Writing'), ('suggest', 'Suggest Improvements')], max_length=20)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_accepted', models.BooleanField(default=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_conversation.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum AI Usage',
                'verbose_name_plural': 'Forum AI Usage Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_blocks', models.JSONField(help_text='Template blocks structure for forum posts')),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Template',
                'verbose_name_plural': 'Post Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RichPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rich_content', models.JSONField(blank=True, help_text='Draftail editor content in Draft.js raw format', null=True)),
                ('content_format', models.CharField(choices=[('plain', 'Plain Text'), ('draftail', 'Rich Content (Draftail)'), ('html', 'HTML')], default='plain', max_length=20)),
                ('ai_assisted', models.BooleanField(default=False, help_text='Whether AI assistance was used in creating this post')),
                ('ai_prompts_used', models.JSONField(blank=True, help_text='AI prompts that were used (for analytics)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rich_content', to='forum_conversation.post')),
            ],
            options={
                'verbose_name': 'Rich Content Post',
                'verbose_name_plural': 'Rich Content Posts',
                'db_table': 'forum_rich_posts',
            },
        ),
    ]
