# Generated by Django 5.2.4 on 2025-08-19 18:22

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0013_auto_20201220_1745'),
        ('forum_integration', '0002_forumaiusage_posttemplate_richpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Main image (automatically resized to max 1200x1200)', upload_to='forum/posts/%Y/%m/')),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('upload_order', models.PositiveIntegerField(default=0, help_text='Order of images in the post (0-based)')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (optional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(help_text='The forum post this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum_conversation.post')),
            ],
            options={
                'verbose_name': 'Forum Post Image',
                'verbose_name_plural': 'Forum Post Images',
                'ordering': ['upload_order', 'created_at'],
                'unique_together': {('post', 'upload_order')},
            },
        ),
    ]
