# Generated by Django 5.2.4 on 2025-08-20 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0013_auto_20201220_1745'),
        ('forum_integration', '0003_forumpostimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('helpful', 'Helpful'), ('thanks', 'Thanks')], help_text='Type of reaction (like, love, helpful, thanks)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reaction is currently active')),
                ('post', models.ForeignKey(help_text='The forum post this reaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum_conversation.post')),
                ('user', models.ForeignKey(help_text='The user who made this reaction', on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Reaction',
                'verbose_name_plural': 'Post Reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'reaction_type'], name='forum_integ_post_id_236755_idx'), models.Index(fields=['user', 'created_at'], name='forum_integ_user_id_eb17bf_idx'), models.Index(fields=['post', 'user'], name='forum_integ_post_id_184bad_idx')],
                'unique_together': {('post', 'user', 'reaction_type')},
            },
        ),
    ]
