# Generated by Django 5.2.7 on 2025-11-13 23:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_calendar', '0002_rename_garden_cale_zip_cod_dbc1b9_idx_garden_cale_zip_cod_1eb673_idx_and_more'),
        ('plant_identification', '0025_remove_diagnosisreminder_diagnosis_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(help_text="USDA zone code (e.g., '7a', '7b')", max_length=5, unique=True)),
                ('temp_min', models.SmallIntegerField(help_text='Minimum average temperature (Fahrenheit)')),
                ('temp_max', models.SmallIntegerField(help_text='Maximum average temperature (Fahrenheit)')),
                ('description', models.TextField(blank=True, help_text='Description of climate characteristics')),
                ('first_frost_date', models.CharField(blank=True, help_text='Average first frost date (MM-DD format)', max_length=10)),
                ('last_frost_date', models.CharField(blank=True, help_text='Average last frost date (MM-DD format)', max_length=10)),
                ('growing_season_days', models.PositiveSmallIntegerField(blank=True, help_text='Average growing season length in days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Growing Zone',
                'verbose_name_plural': 'Growing Zones',
                'ordering': ['zone_code'],
            },
        ),
        migrations.CreateModel(
            name='GardenBed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of this garden bed', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this bed')),
                ('bed_type', models.CharField(choices=[('raised', 'Raised Bed'), ('in_ground', 'In-Ground Bed'), ('container', 'Container Garden'), ('greenhouse', 'Greenhouse'), ('indoor', 'Indoor Growing'), ('hydroponic', 'Hydroponic System'), ('other', 'Other')], default='raised', help_text='Type of garden bed', max_length=20)),
                ('length_inches', models.PositiveIntegerField(blank=True, help_text='Length in inches', null=True)),
                ('width_inches', models.PositiveIntegerField(blank=True, help_text='Width in inches', null=True)),
                ('depth_inches', models.PositiveIntegerField(blank=True, help_text='Depth/height in inches', null=True)),
                ('layout_data', models.JSONField(blank=True, default=dict, help_text='JSON data for plant positions on canvas (x, y coordinates)')),
                ('location_name', models.CharField(blank=True, help_text="Location description (e.g., 'Backyard', 'Front Porch')", max_length=200)),
                ('sun_exposure', models.CharField(blank=True, choices=[('full_sun', 'Full Sun (6+ hours)'), ('partial_sun', 'Partial Sun (4-6 hours)'), ('partial_shade', 'Partial Shade (2-4 hours)'), ('full_shade', 'Full Shade (<2 hours)')], help_text='Daily sun exposure', max_length=20)),
                ('hardiness_zone', models.CharField(blank=True, help_text='USDA Hardiness Zone', max_length=5)),
                ('soil_type', models.CharField(blank=True, help_text="Soil type (e.g., 'Clay', 'Sandy', 'Loam')", max_length=100)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=1, help_text='Soil pH level (0-14)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this bed currently in use?')),
                ('notes', models.TextField(blank=True, help_text='General notes about this bed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this garden bed', on_delete=django.db.models.deletion.CASCADE, related_name='garden_beds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garden Bed',
                'verbose_name_plural': 'Garden Beds',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', primary_key=True, serialize=False, unique=True)),
                ('common_name', models.CharField(help_text='Common name of plant', max_length=200)),
                ('scientific_name', models.CharField(blank=True, help_text='Scientific name (if known)', max_length=200)),
                ('variety', models.CharField(blank=True, help_text='Specific variety or cultivar', max_length=200)),
                ('planted_date', models.DateField(help_text='Date this plant was planted/sown')),
                ('source', models.CharField(blank=True, help_text='Where plant came from (nursery, seed packet, gift, etc.)', max_length=200)),
                ('position_x', models.PositiveIntegerField(blank=True, help_text='X coordinate on canvas (for visual layout)', null=True)),
                ('position_y', models.PositiveIntegerField(blank=True, help_text='Y coordinate on canvas (for visual layout)', null=True)),
                ('health_status', models.CharField(choices=[('thriving', 'Thriving'), ('healthy', 'Healthy'), ('fair', 'Fair/OK'), ('struggling', 'Struggling'), ('diseased', 'Diseased'), ('pest_damage', 'Pest Damage'), ('dying', 'Dying'), ('dead', 'Dead/Removed')], default='healthy', help_text='Current health status', max_length=20)),
                ('growth_stage', models.CharField(blank=True, choices=[('seed', 'Seed'), ('germination', 'Germination'), ('seedling', 'Seedling'), ('vegetative', 'Vegetative Growth'), ('budding', 'Budding'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting/Producing'), ('harvest', 'Harvest Ready'), ('dormant', 'Dormant'), ('declining', 'Declining')], help_text='Current growth stage', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this plant still growing/alive?')),
                ('removed_date', models.DateField(blank=True, help_text='Date plant was removed/died', null=True)),
                ('removal_reason', models.CharField(blank=True, help_text='Why plant was removed (harvested, died, etc.)', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='General notes about this plant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden_bed', models.ForeignKey(help_text='Garden bed this plant is in', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='garden_calendar.gardenbed')),
                ('plant_species', models.ForeignKey(blank=True, help_text='Link to identified plant species (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_instances', to='plant_identification.plantspecies')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['garden_bed', '-planted_date'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(help_text='Date of harvest')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity harvested', max_digits=8)),
                ('unit', models.CharField(choices=[('count', 'Count (individual items)'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('bunch', 'Bunches'), ('basket', 'Baskets')], default='count', help_text='Unit of measurement', max_length=10)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='Quality rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Notes about this harvest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(help_text='Plant that was harvested', on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='garden_calendar.plant')),
            ],
            options={
                'verbose_name': 'Harvest',
                'verbose_name_plural': 'Harvests',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', primary_key=True, serialize=False, unique=True)),
                ('task_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('deadheading', 'Deadheading'), ('repotting', 'Repotting/Transplanting'), ('pest_check', 'Pest Inspection'), ('disease_check', 'Disease Check'), ('soil_amendment', 'Soil Amendment'), ('mulching', 'Mulching'), ('staking', 'Staking/Support'), ('harvesting', 'Harvesting'), ('winterization', 'Winter Preparation'), ('spring_cleanup', 'Spring Cleanup'), ('custom', 'Custom Task')], help_text='Type of care task', max_length=20)),
                ('custom_task_name', models.CharField(blank=True, help_text="Custom task name (if task_type='custom')", max_length=200)),
                ('title', models.CharField(help_text='Task title/description', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=10)),
                ('scheduled_date', models.DateTimeField(help_text='When this task should be done')),
                ('is_recurring', models.BooleanField(default=False, help_text='Does this task repeat?')),
                ('recurrence_interval_days', models.PositiveIntegerField(blank=True, help_text='How often to repeat (in days)', null=True)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='When to stop recurring (optional)', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Has this task been completed?')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task was completed', null=True)),
                ('skipped', models.BooleanField(default=False, help_text='Was this task skipped?')),
                ('skip_reason', models.TextField(blank=True, help_text='Why task was skipped')),
                ('skipped_at', models.DateTimeField(blank=True, help_text='When task was skipped', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Has notification been sent?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who completed this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_care_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='created_care_tasks', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(help_text='Plant this task is for', on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='garden_calendar.plant')),
            ],
            options={
                'verbose_name': 'Care Task',
                'verbose_name_plural': 'Care Tasks',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('activity_type', models.CharField(blank=True, help_text='Type of activity (watering, fertilizing, etc.)', max_length=50)),
                ('content', models.TextField(help_text='Log entry content/observations')),
                ('temperature', models.SmallIntegerField(blank=True, help_text='Temperature at time of log (Fahrenheit)', null=True)),
                ('humidity', models.PositiveSmallIntegerField(blank=True, help_text='Humidity percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing logs')),
                ('user', models.ForeignKey(help_text='User who created this log', on_delete=django.db.models.deletion.CASCADE, related_name='plant_care_logs', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(help_text='Plant this log entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='garden_calendar.plant')),
            ],
            options={
                'verbose_name': 'Care Log Entry',
                'verbose_name_plural': 'Care Log Entries',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Plant photograph', upload_to='garden_plants/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Image caption/description', max_length=200)),
                ('taken_date', models.DateField(auto_now_add=True, help_text='Date photo was taken')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary/featured image?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(help_text='Plant this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden_calendar.plant')),
            ],
            options={
                'verbose_name': 'Plant Image',
                'verbose_name_plural': 'Plant Images',
                'ordering': ['-taken_date'],
            },
        ),
        migrations.AddIndex(
            model_name='gardenbed',
            index=models.Index(fields=['owner', '-updated_at'], name='garden_cale_owner_i_7c376c_idx'),
        ),
        migrations.AddIndex(
            model_name='gardenbed',
            index=models.Index(fields=['owner', 'is_active'], name='garden_cale_owner_i_05c963_idx'),
        ),
        migrations.AddIndex(
            model_name='gardenbed',
            index=models.Index(fields=['hardiness_zone'], name='garden_cale_hardine_1ddfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['garden_bed', '-planted_date'], name='garden_cale_garden__26d93c_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['garden_bed', 'is_active'], name='garden_cale_garden__912f38_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['health_status'], name='garden_cale_health__88800e_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['common_name'], name='garden_cale_common__548ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['plant', '-harvest_date'], name='garden_cale_plant_i_642978_idx'),
        ),
        migrations.AddIndex(
            model_name='caretask',
            index=models.Index(fields=['plant', 'scheduled_date'], name='garden_cale_plant_i_b4cbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='caretask',
            index=models.Index(fields=['created_by', 'completed', 'skipped'], name='garden_cale_created_188cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='caretask',
            index=models.Index(fields=['task_type', 'scheduled_date'], name='garden_cale_task_ty_9dc27a_idx'),
        ),
        migrations.AddIndex(
            model_name='caretask',
            index=models.Index(fields=['scheduled_date', 'completed'], name='garden_cale_schedul_d7c874_idx'),
        ),
        migrations.AddIndex(
            model_name='carelog',
            index=models.Index(fields=['plant', '-log_date'], name='garden_cale_plant_i_f8dc03_idx'),
        ),
        migrations.AddIndex(
            model_name='carelog',
            index=models.Index(fields=['user', '-log_date'], name='garden_cale_user_id_1030d7_idx'),
        ),
    ]
