# Generated by Django 5.2.7 on 2025-11-14 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_calendar', '0003_growingzone_gardenbed_plant_harvest_caretask_carelog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carelog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='carelog',
            name='id',
        ),
        migrations.AddField(
            model_name='carelog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of materials/service', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='carelog',
            name='hours_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours spent on this activity', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='carelog',
            name='materials_used',
            field=models.TextField(blank=True, help_text='Materials or products used'),
        ),
        migrations.AddField(
            model_name='carelog',
            name='notes',
            field=models.TextField(blank=True, help_text='Log entry content/observations'),
        ),
        migrations.AddField(
            model_name='carelog',
            name='plant_health_after',
            field=models.CharField(blank=True, choices=[('thriving', 'Thriving'), ('healthy', 'Healthy'), ('fair', 'Fair/OK'), ('struggling', 'Struggling'), ('diseased', 'Diseased'), ('pest_damage', 'Pest Damage'), ('dying', 'Dying'), ('dead', 'Dead/Removed')], help_text='Plant health status after this care activity', max_length=20),
        ),
        migrations.AddField(
            model_name='carelog',
            name='plant_health_before',
            field=models.CharField(blank=True, choices=[('thriving', 'Thriving'), ('healthy', 'Healthy'), ('fair', 'Fair/OK'), ('struggling', 'Struggling'), ('diseased', 'Diseased'), ('pest_damage', 'Pest Damage'), ('dying', 'Dying'), ('dead', 'Dead/Removed')], help_text='Plant health status before this care activity', max_length=20),
        ),
        migrations.AddField(
            model_name='carelog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='carelog',
            name='weather_conditions',
            field=models.TextField(blank=True, help_text='Weather conditions during activity'),
        ),
    ]
