# Generated by Django 5.2 on 2025-11-14
# Custom migration to add UUID primary key to PlantImage model
"""
Migration to swap PlantImage primary key from auto-incrementing 'id' to UUID.

⚠️ IMPORTANT: PostgreSQL primary-key swap ⚠️

This migration uses PostgreSQL-specific raw SQL commands (ALTER TABLE, DROP CONSTRAINT).
SQLite has limited ALTER TABLE support and cannot swap primary keys this way, so SQLite
development databases keep the legacy integer `id` column physically present while Django's
migration state uses `uuid` as the model primary key.

For Production (PostgreSQL):
    python manage.py migrate garden_calendar

For Development (SQLite):
    python manage.py migrate

Migration Steps:
1. Add UUID field as nullable and non-unique (handles existing data safely)
2. Populate UUIDs for existing records (RunPython)
3. Make UUID non-nullable
4. Drop old primary key constraint (raw SQL - PostgreSQL only)
5. Add new primary key on UUID (raw SQL - PostgreSQL only)
6. Remove old 'id' field

Reversibility:
- Not reversible: dropping the old integer 'id' column is destructive.
- Restore from backup if rollback to the integer primary key is required.
"""

from django.db import migrations, models
from typing import Any
import uuid


# Whitelist of allowed tables (defense in depth - SQL injection prevention)
ALLOWED_TABLES = {'garden_calendar_plantimage'}


def validate_table_name(table_name: str) -> str:
    """
    Validate table name against whitelist for SQL injection prevention.

    Pattern: docs/patterns/security/input-validation.md
    Defense in depth: Even though table name is hardcoded, whitelist validation
    provides additional safety layer per CLAUDE.md migration security pattern.
    """
    if table_name not in ALLOWED_TABLES:
        raise ValueError(f"[SECURITY] Table not in whitelist: {table_name}")
    return table_name


def generate_uuids_for_existing_images(apps: Any, schema_editor: Any) -> None:
    """
    Generate UUIDs for any existing PlantImage records.
    This function will be called during migration if there are existing records.
    """
    PlantImage = apps.get_model('garden_calendar', 'PlantImage')
    for image in PlantImage.objects.all():
        if not image.uuid:
            image.uuid = uuid.uuid4()
            image.save(update_fields=['uuid'])


def quote_identifier(identifier: str) -> str:
    """
    Safely quote a whitelisted PostgreSQL identifier for migration SQL.

    Django's RunSQL expects strings or (sql, params) tuples. Passing
    psycopg2.sql.Composed objects is stringified as ``Composed(...)`` by the
    schema editor, which breaks fresh database migrations.
    """
    validated_identifier = validate_table_name(identifier)
    return f'"{validated_identifier}"'


PLANTIMAGE_TABLE = quote_identifier('garden_calendar_plantimage')
PLANTIMAGE_PK = '"garden_calendar_plantimage_pkey"'
PLANTIMAGE_UUID_COLUMN = '"uuid"'
PLANTIMAGE_ID_COLUMN = '"id"'


def swap_plantimage_primary_key(apps: Any, schema_editor: Any) -> None:
    """
    Swap PlantImage primary key from integer id to uuid on PostgreSQL.

    SQLite cannot drop or add primary keys in-place. For SQLite development
    databases, the Django migration state still moves the model primary key to
    uuid, but the physical table keeps the ignored legacy id column.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        f'ALTER TABLE {PLANTIMAGE_TABLE} DROP CONSTRAINT IF EXISTS {PLANTIMAGE_PK} CASCADE;'
    )
    schema_editor.execute(
        f'ALTER TABLE {PLANTIMAGE_TABLE} ADD PRIMARY KEY ({PLANTIMAGE_UUID_COLUMN});'
    )
    schema_editor.execute(f'ALTER TABLE {PLANTIMAGE_TABLE} DROP COLUMN {PLANTIMAGE_ID_COLUMN};')


class Migration(migrations.Migration):

    dependencies = [
        ('garden_calendar', '0004_add_carelog_uuid_and_fields'),
    ]

    operations = [
        # Step 1: Add UUID field as nullable and non-unique first (to handle existing data)
        migrations.AddField(
            model_name='plantimage',
            name='uuid',
            field=models.UUIDField(
                editable=False,
                null=True,  # Temporarily nullable
                help_text="Unique identifier for secure references"
            ),
        ),

        # Step 2: Populate UUIDs for any existing records
        migrations.RunPython(
            generate_uuids_for_existing_images,
            reverse_code=migrations.RunPython.noop
        ),

        # Step 3: Make UUID non-nullable
        migrations.AlterField(
            model_name='plantimage',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                help_text="Unique identifier for secure references"
            ),
        ),

        # Step 4-6: Swap database primary key and synchronize Django migration state.
        # Pattern: CLAUDE.md Migration SQL Injection Prevention (whitelist + static quoted identifiers)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    swap_plantimage_primary_key,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='plantimage',
                    name='uuid',
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        primary_key=True,
                        help_text="Unique identifier for secure references"
                    ),
                ),
                migrations.RemoveField(
                    model_name='plantimage',
                    name='id',
                ),
            ],
        ),
    ]
