# Generated by Django 6.0.5 on 2026-06-02
#
# State-only field change: adds `choices` to CareLog.activity_type so that
# get_activity_type_display() exists (the API's activity_type_display field) and
# drf-spectacular emits an enum. `choices` is not a DB constraint, so this alters
# no table — existing rows with out-of-list values still read fine.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden_calendar", "0005_add_plantimage_uuid_primary_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carelog",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("watering", "Watering"),
                    ("fertilizing", "Fertilizing"),
                    ("pruning", "Pruning"),
                    ("harvesting", "Harvesting"),
                    ("planting", "Planting"),
                    ("transplanting", "Transplanting"),
                    ("repotting", "Repotting"),
                    ("mulching", "Mulching"),
                    ("weeding", "Weeding"),
                    ("treatment", "Treatment"),
                    ("pest_control", "Pest Control"),
                    ("observation", "Observation"),
                    ("other", "Other"),
                ],
                help_text="Type of activity (watering, fertilizing, etc.)",
                max_length=50,
            ),
        ),
    ]
