# Generated by Django 6.0.5 on 2026-06-05 03:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden_calendar", "0006_carelog_activity_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for secure references",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
