# Generated by Django 5.2.7 on 2025-11-14 23:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant_identification', '0025_remove_diagnosisreminder_diagnosis_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCareLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('common_names', models.JSONField(default=list, help_text='List of common names')),
                ('family', models.CharField(blank=True, max_length=100)),
                ('sunlight', models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_shade', 'Partial Shade'), ('full_shade', 'Full Shade')], max_length=20)),
                ('water_needs', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('soil_type', models.CharField(blank=True, max_length=200)),
                ('hardiness_zones', models.JSONField(default=list, help_text="USDA hardiness zones (e.g., ['5a', '9b'])")),
                ('care_instructions', models.TextField(blank=True)),
                ('watering_frequency_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fertilizing_frequency_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('pruning_frequency_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('companion_plants', models.JSONField(default=list, help_text='List of compatible plant species')),
                ('enemy_plants', models.JSONField(default=list, help_text='List of incompatible plant species')),
                ('common_pests', models.JSONField(default=list, help_text='List of common pests for this plant')),
                ('common_diseases', models.JSONField(default=list, help_text='List of common diseases')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant Care Library Entry',
                'verbose_name_plural': 'Plant Care Library Entries',
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dimensions', models.JSONField(help_text="Garden dimensions in format: {width: 20, height: 10, unit: 'ft'}")),
                ('layout_data', models.JSONField(default=dict, help_text='Plant positions and canvas metadata')),
                ('location', models.JSONField(blank=True, help_text='Location data: {lat: float, lng: float, city: str}', null=True)),
                ('climate_zone', models.CharField(blank=True, help_text="USDA hardiness zone (e.g., '7a', '9b')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Featured in community garden gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garden',
                'verbose_name_plural': 'Gardens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('planted_date', models.DateField()),
                ('position', models.JSONField(help_text='Position on canvas in format: {x: 5, y: 10}')),
                ('image', models.ImageField(blank=True, null=True, upload_to='garden_plants/')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this plant')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('needs_attention', 'Needs Attention'), ('diseased', 'Diseased'), ('dead', 'Dead')], default='healthy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='garden.garden')),
                ('plant_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_planner_instances', to='plant_identification.plantspecies')),
            ],
            options={
                'verbose_name': 'Garden Plant',
                'verbose_name_plural': 'Garden Plants',
                'ordering': ['garden', '-planted_date'],
            },
        ),
        migrations.CreateModel(
            name='CareReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('repotting', 'Repotting'), ('pest_check', 'Pest Check'), ('custom', 'Custom')], max_length=20)),
                ('custom_type_name', models.CharField(blank=True, help_text="Custom reminder type name (if type is 'custom')", max_length=100)),
                ('scheduled_date', models.DateTimeField()),
                ('recurring', models.BooleanField(default=False)),
                ('interval_days', models.IntegerField(blank=True, help_text='Days between recurring reminders', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_care_reminders', to=settings.AUTH_USER_MODEL)),
                ('garden_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='garden.gardenplant')),
            ],
            options={
                'verbose_name': 'Care Reminder',
                'verbose_name_plural': 'Care Reminders',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('weather_data', models.JSONField(blank=True, help_text='Weather snapshot: {temp, conditions, humidity, etc.}', null=True)),
                ('tags', models.JSONField(default=list, help_text='List of tags for filtering entries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='garden.garden')),
                ('garden_plant', models.ForeignKey(blank=True, help_text='Optional: Link to specific plant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='garden.gardenplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal_entries/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Image',
                'verbose_name_plural': 'Journal Images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_type', models.CharField(help_text='Type of pest or disease', max_length=200)),
                ('description', models.TextField()),
                ('identified_date', models.DateField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('treatment', models.TextField(blank=True)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_issues', to='garden.gardenplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pest Issue',
                'verbose_name_plural': 'Pest Issues',
                'ordering': ['-identified_date'],
            },
        ),
        migrations.CreateModel(
            name='PestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pest_issues/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pest_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.pestissue')),
            ],
            options={
                'verbose_name': 'Pest Image',
                'verbose_name_plural': 'Pest Images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('planting', 'Planting'), ('maintenance', 'Maintenance'), ('harvesting', 'Harvesting'), ('preparation', 'Preparation'), ('other', 'Other')], max_length=20)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('year_round', 'Year Round')], max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(blank=True, help_text='Optional: Link to specific garden', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='garden.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gardening Task',
                'verbose_name_plural': 'Gardening Tasks',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='garden',
            index=models.Index(fields=['user', '-updated_at'], name='garden_gard_user_id_adf17c_idx'),
        ),
        migrations.AddIndex(
            model_name='garden',
            index=models.Index(fields=['visibility', 'featured'], name='garden_gard_visibil_86823a_idx'),
        ),
        migrations.AddIndex(
            model_name='carereminder',
            index=models.Index(fields=['user', 'scheduled_date', 'completed'], name='garden_care_user_id_e78502_idx'),
        ),
        migrations.AddIndex(
            model_name='carereminder',
            index=models.Index(fields=['notification_sent', 'scheduled_date'], name='garden_care_notific_43ce67_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-date'], name='garden_jour_user_id_f5bfcd_idx'),
        ),
    ]
