# Generated by Django 5.2.4 on 2025-08-11 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0005_alter_plantspeciespage_plant_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCareInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', unique=True)),
                ('plant_scientific_name', models.CharField(help_text='Scientific name of the plant', max_length=200)),
                ('plant_common_name', models.CharField(blank=True, help_text='Common name of the plant', max_length=200)),
                ('plant_family', models.CharField(blank=True, help_text='Plant family', max_length=100)),
                ('care_instructions_data', models.JSONField(help_text='Full care instructions data from the API')),
                ('personal_notes', models.TextField(blank=True, help_text="User's personal notes and experiences with this plant")),
                ('custom_nickname', models.CharField(blank=True, help_text="User's custom nickname for this plant", max_length=100)),
                ('care_difficulty_experienced', models.CharField(blank=True, choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult')], help_text="User's experienced difficulty level", max_length=20, null=True)),
                ('current_status', models.CharField(choices=[('planning', 'Planning to Get'), ('newly_acquired', 'Recently Acquired'), ('thriving', 'Thriving'), ('struggling', 'Having Issues'), ('recovered', 'Recovered from Problems'), ('lost', 'Plant Lost')], default='planning', help_text="Current status of user's plant", max_length=20)),
                ('share_with_community', models.BooleanField(default=False, help_text='Share this care experience with the community')),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite care card')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Last time user viewed this care card', null=True)),
                ('plant_species', models.ForeignKey(blank=True, help_text='Plant species this care card is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_identification.plantspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_care_instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'plant_scientific_name')},
            },
        ),
    ]
