# Generated by Django 5.2.4 on 2025-08-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0006_savedcareinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantidentificationresult',
            name='ai_care_instructions',
            field=models.JSONField(blank=True, help_text='AI-generated care instructions for this plant', null=True),
        ),
        migrations.AddField(
            model_name='plantidentificationresult',
            name='care_instructions_generated_at',
            field=models.DateTimeField(blank=True, help_text='When care instructions were generated', null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='care_instructions_json',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated or custom care instructions for this plant'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='from_identification_result',
            field=models.ForeignKey(blank=True, help_text='Specific identification result that was accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_plants', to='plant_identification.plantidentificationresult'),
        ),
    ]
