# Generated by Django 5.2.4 on 2025-08-19 19:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0007_plantidentificationresult_ai_care_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspeciespage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'plant_identification/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'plant_identification/blocks/paragraph.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'plant_identification/blocks/image.html'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 8, 'min_num': 2}), 6: ('wagtail.blocks.StructBlock', [[('gallery_title', 3), ('images', 5)]], {'icon': 'image', 'template': 'plant_identification/blocks/gallery.html'})}, help_text='Detailed plant information and care instructions'),
        ),
        migrations.DeleteModel(
            name='PlantCareGuide',
        ),
    ]
