# Generated by Django 5.2.4 on 2025-08-20 00:31

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0008_remove_plant_care_guide'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspeciespage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('care_tip', 5), ('seasonal_care', 8), ('problem_solution', 9), ('image', 10), ('gallery', 14)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'plant_identification/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'plant_identification/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')]}), 5: ('wagtail.blocks.StructBlock', [[('tip_title', 2), ('tip_content', 3), ('difficulty_level', 4)]], {'icon': 'help', 'template': 'plant_identification/blocks/care_tip.html'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn/Fall'), ('winter', 'Winter')]}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('season', 6), ('care_instructions', 3), ('special_notes', 7)]], {'icon': 'date', 'template': 'plant_identification/blocks/seasonal_care.html'}), 9: ('wagtail.blocks.StructBlock', [[('problem', 2), ('symptoms', 3), ('solution', 3), ('prevention', 7)]], {'icon': 'warning', 'template': 'plant_identification/blocks/problem_solution.html'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'plant_identification/blocks/image.html'}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {'max_num': 8, 'min_num': 2}), 14: ('wagtail.blocks.StructBlock', [[('gallery_title', 11), ('images', 13)]], {'icon': 'image', 'template': 'plant_identification/blocks/gallery.html'})}, help_text='Detailed plant information and care instructions'),
        ),
        migrations.CreateModel(
            name='PlantCareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_difficulty', models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult')], default='moderate', max_length=20)),
                ('quick_care_summary', wagtail.fields.RichTextField(help_text='Brief summary of care requirements')),
                ('care_content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('care_tip', 5), ('seasonal_care', 8), ('problem_solution', 9), ('image', 10), ('gallery', 14)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'plant_identification/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'plant_identification/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')]}), 5: ('wagtail.blocks.StructBlock', [[('tip_title', 2), ('tip_content', 3), ('difficulty_level', 4)]], {'icon': 'help', 'template': 'plant_identification/blocks/care_tip.html'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn/Fall'), ('winter', 'Winter')]}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('season', 6), ('care_instructions', 3), ('special_notes', 7)]], {'icon': 'date', 'template': 'plant_identification/blocks/seasonal_care.html'}), 9: ('wagtail.blocks.StructBlock', [[('problem', 2), ('symptoms', 3), ('solution', 3), ('prevention', 7)]], {'icon': 'warning', 'template': 'plant_identification/blocks/problem_solution.html'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'plant_identification/blocks/image.html'}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {'max_num': 8, 'min_num': 2}), 14: ('wagtail.blocks.StructBlock', [[('gallery_title', 11), ('images', 13)]], {'icon': 'image', 'template': 'plant_identification/blocks/gallery.html'})}, help_text='Detailed care instructions using content blocks')),
                ('light_description', models.TextField(blank=True, help_text='Detailed light requirements description')),
                ('watering_description', models.TextField(blank=True, help_text='Detailed watering instructions')),
                ('soil_description', models.TextField(blank=True, help_text='Soil requirements and recommendations')),
                ('temperature_description', models.TextField(blank=True, help_text='Temperature preferences and tolerance')),
                ('humidity_description', models.TextField(blank=True, help_text='Humidity requirements')),
                ('fertilizing_description', models.TextField(blank=True, help_text='Fertilizing schedule and recommendations')),
                ('propagation_methods', models.TextField(blank=True, help_text='How to propagate this plant')),
                ('common_problems', models.TextField(blank=True, help_text='Common issues and solutions')),
                ('seasonal_notes', models.TextField(blank=True, help_text='Special seasonal care considerations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this care guide')),
                ('plant_species', models.OneToOneField(help_text='Plant species this care guide is for', on_delete=django.db.models.deletion.CASCADE, related_name='care_guide', to='plant_identification.plantspecies')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Tags for categorizing care guides', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Plant Care Guide',
                'verbose_name_plural': 'Plant Care Guides',
                'ordering': ['plant_species__scientific_name'],
            },
        ),
    ]
