# Generated by Django 5.2.7 on 2025-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0011_batchidentificationrequest_batchidentificationimage_and_more'),
    ]

    operations = [
        # PlantIdentificationRequest indexes
        migrations.AddIndex(
            model_name='plantidentificationrequest',
            index=models.Index(fields=['user', '-created_at'], name='idx_request_user_created'),
        ),
        migrations.AddIndex(
            model_name='plantidentificationrequest',
            index=models.Index(fields=['status', '-created_at'], name='idx_request_status_created'),
        ),

        # PlantIdentificationResult indexes
        migrations.AddIndex(
            model_name='plantidentificationresult',
            index=models.Index(fields=['confidence_score', '-created_at'], name='idx_result_confidence'),
        ),
        migrations.AddIndex(
            model_name='plantidentificationresult',
            index=models.Index(fields=['request', 'confidence_score'], name='idx_result_request_conf'),
        ),

        # PlantSpecies indexes
        migrations.AddIndex(
            model_name='plantspecies',
            index=models.Index(fields=['scientific_name'], name='idx_species_scientific'),
        ),
        migrations.AddIndex(
            model_name='plantspecies',
            index=models.Index(fields=['identification_count', '-created_at'], name='idx_species_popularity'),
        ),

        # UserPlant indexes
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['user', '-acquisition_date'], name='idx_userplant_user_date'),
        ),
        migrations.AddIndex(
            model_name='userplant',
            index=models.Index(fields=['species', 'user'], name='idx_userplant_species_user'),
        ),
    ]
