# Generated by Django 5.2.7 on 2025-10-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0013_add_search_gin_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plantidentificationrequest',
            name='idx_request_user_created',
        ),
        migrations.RemoveIndex(
            model_name='plantidentificationrequest',
            name='idx_request_status_created',
        ),
        migrations.RemoveIndex(
            model_name='plantidentificationresult',
            name='idx_result_confidence',
        ),
        migrations.RemoveIndex(
            model_name='plantidentificationresult',
            name='idx_result_request_conf',
        ),
        migrations.RemoveIndex(
            model_name='plantspecies',
            name='idx_species_scientific',
        ),
        migrations.RemoveIndex(
            model_name='plantspecies',
            name='idx_species_popularity',
        ),
        migrations.RemoveIndex(
            model_name='userplant',
            name='idx_userplant_user_date',
        ),
        migrations.RemoveIndex(
            model_name='userplant',
            name='idx_userplant_species_user',
        ),
    ]
