# Generated by Django 5.2.7 on 2025-10-28 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0015_add_confidence_score_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantidentificationresult',
            name='identified_species',
            field=models.ForeignKey(blank=True, help_text='Identified species from database. SET_NULL preserves research data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_results', to='plant_identification.plantspecies'),
        ),
        migrations.AlterField(
            model_name='savedcareinstructions',
            name='plant_species',
            field=models.ForeignKey(blank=True, help_text='Plant species this care card is for. SET_NULL preserves saved care instructions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_identification.plantspecies'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Species from database. SET_NULL preserves user plant records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plants', to='plant_identification.plantspecies'),
        ),
    ]
