# Generated by Django 5.2.7 on 2025-11-02 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0019_add_not_null_constraints_step3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', unique=True)),
                ('plant_scientific_name', models.CharField(help_text='Scientific name of the affected plant', max_length=200)),
                ('plant_common_name', models.CharField(blank=True, help_text='Common name of the affected plant', max_length=200)),
                ('custom_nickname', models.CharField(blank=True, help_text="User's custom nickname for this plant", max_length=100)),
                ('disease_name', models.CharField(help_text='Name of the diagnosed disease', max_length=200)),
                ('disease_type', models.CharField(choices=[('fungal', 'Fungal Disease'), ('bacterial', 'Bacterial Disease'), ('viral', 'Viral Disease'), ('pest', 'Pest/Insect Damage'), ('abiotic', 'Abiotic/Environmental'), ('deficiency', 'Nutrient Deficiency'), ('toxicity', 'Toxicity/Poisoning')], help_text='Type of disease', max_length=20)),
                ('severity_assessment', models.CharField(choices=[('mild', 'Mild - Early symptoms'), ('moderate', 'Moderate - Noticeable damage'), ('severe', 'Severe - Significant damage'), ('critical', 'Critical - Plant in danger')], help_text='Severity of the disease', max_length=20)),
                ('confidence_score', models.FloatField(help_text='AI confidence score (0.0 to 1.0)')),
                ('care_instructions', models.JSONField(blank=True, default=list, help_text='Structured care instructions as StreamField-compatible JSON (list of blocks)')),
                ('personal_notes', models.TextField(blank=True, help_text="User's personal notes about this diagnosis")),
                ('treatment_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'Treatment in Progress'), ('successful', 'Successfully Treated'), ('failed', 'Treatment Failed'), ('monitoring', 'Monitoring Progress')], default='not_started', help_text='Current treatment status', max_length=20)),
                ('plant_recovered', models.BooleanField(blank=True, help_text='Did the plant recover? (null = unknown/in progress)', null=True)),
                ('share_with_community', models.BooleanField(default=False, help_text='Share this diagnosis experience with the community')),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite diagnosis card')),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When this diagnosis card was saved')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this card was updated')),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Last time user viewed this card', null=True)),
                ('diagnosis_result', models.ForeignKey(help_text='Original diagnosis result', on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_cards', to='plant_identification.plantdiseaseresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure references', unique=True)),
                ('reminder_type', models.CharField(choices=[('check_progress', 'Check Recovery Progress'), ('treatment_step', 'Complete Treatment Step'), ('follow_up', 'General Follow-up'), ('reapply', 'Reapply Treatment')], default='check_progress', help_text='Type of reminder', max_length=20)),
                ('reminder_title', models.CharField(help_text='Title of the reminder', max_length=200)),
                ('reminder_message', models.TextField(blank=True, help_text='Custom message for this reminder')),
                ('scheduled_date', models.DateTimeField(help_text='When to send this reminder')),
                ('sent', models.BooleanField(default=False, help_text='Has this reminder been sent?')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Has the user acknowledged this reminder?')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the user acknowledged the reminder', null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='If snoozed, when to remind again', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this reminder still active?')),
                ('cancelled', models.BooleanField(default=False, help_text='Has this reminder been cancelled?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this reminder was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this reminder was updated')),
                ('diagnosis_card', models.ForeignKey(help_text='Diagnosis card this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='plant_identification.diagnosiscard')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosiscard',
            index=models.Index(fields=['user', '-saved_at'], name='plant_ident_user_id_1bbf12_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscard',
            index=models.Index(fields=['treatment_status'], name='plant_ident_treatme_c47e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscard',
            index=models.Index(fields=['-saved_at'], name='plant_ident_saved_a_0a7c8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosiscard',
            unique_together={('user', 'diagnosis_result')},
        ),
        migrations.AddIndex(
            model_name='diagnosisreminder',
            index=models.Index(fields=['diagnosis_card', 'scheduled_date'], name='plant_ident_diagnos_9a7d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisreminder',
            index=models.Index(fields=['scheduled_date', 'sent'], name='plant_ident_schedul_0f3a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisreminder',
            index=models.Index(fields=['sent', 'is_active'], name='plant_ident_sent_078eae_idx'),
        ),
    ]
