# Generated by Django 5.2.7 on 2025-11-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identification', '0024_change_disease_result_cascade_to_set_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisreminder',
            name='diagnosis_card',
        ),
        migrations.DeleteModel(
            name='DiagnosisCard',
        ),
        migrations.DeleteModel(
            name='DiagnosisReminder',
        ),
    ]
