# Generated by Django 5.2.4 on 2025-08-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_simple_search_vectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='content_type',
            field=models.CharField(choices=[('all', 'All Content'), ('forum', 'Forum Posts'), ('plants', 'Plant Species'), ('blog', 'Blog Posts'), ('diseases', 'Plant Diseases'), ('care_guides', 'Care Guides')], default='all', help_text='Type of content being searched', max_length=100),
        ),
    ]
