# Generated by Django 5.2.7 on 2025-11-03 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category. PROTECT prevents accidental deletion of category hierarchies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='forum.category'),
        ),
    ]
