# Generated by Django 5.2.7 on 2025-11-05 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_category_parent_protect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key for security', primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('thread', 'Thread')], help_text='Type of content being flagged (post or thread)', max_length=20)),
                ('flag_reason', models.CharField(choices=[('spam', 'Spam or Advertising'), ('offensive', 'Offensive or Inappropriate Content'), ('off_topic', 'Off-Topic'), ('misinformation', 'Misinformation'), ('duplicate', 'Duplicate Content'), ('low_quality', 'Low Quality'), ('other', 'Other')], default='other', help_text='Reason for flagging', max_length=50)),
                ('explanation', models.TextField(blank=True, help_text='Optional detailed explanation from reporter', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (No Action Needed)'), ('rejected', 'Rejected (Flag Invalid)'), ('removed', 'Content Removed')], default='pending', help_text='Current moderation status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When flag was reviewed', null=True)),
                ('moderator_notes', models.TextField(blank=True, help_text='Internal notes from moderator', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flagged Content',
                'verbose_name_plural': 'Flagged Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key for security', primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve', 'Approve (No Violation)'), ('reject', 'Reject Flag'), ('remove_post', 'Remove Post'), ('remove_thread', 'Remove Thread'), ('lock_thread', 'Lock Thread'), ('warning', 'Issue Warning to User')], help_text='Type of action taken', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Reason for taking this action', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='post',
            field=models.ForeignKey(blank=True, help_text="Flagged post (if content_type is 'post')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.post'),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='reporter',
            field=models.ForeignKey(help_text='User who submitted the flag', on_delete=django.db.models.deletion.CASCADE, related_name='flags_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who reviewed this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='thread',
            field=models.ForeignKey(blank=True, help_text="Flagged thread (if content_type is 'thread')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.thread'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='affected_user',
            field=models.ForeignKey(blank=True, help_text='User affected by this action (post/thread author)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='flag',
            field=models.ForeignKey(help_text='Associated flag that triggered this action', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='forum.flaggedcontent'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(help_text='Moderator who took the action', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['status', '-created_at'], name='forum_flag_status_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['content_type', 'status'], name='forum_flag_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['reporter', '-created_at'], name='forum_flag_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['reviewed_by', '-reviewed_at'], name='forum_flag_reviewer_idx'),
        ),
        migrations.AddConstraint(
            model_name='flaggedcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type', 'post'), ('post__isnull', False), ('thread__isnull', True)), models.Q(('content_type', 'thread'), ('thread__isnull', False), ('post__isnull', True)), _connector='OR'), name='forum_flag_content_type_consistency'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['flag', '-created_at'], name='forum_modaction_flag_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', '-created_at'], name='forum_modaction_mod_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['affected_user', '-created_at'], name='forum_modaction_user_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='forum_modaction_type_idx'),
        ),
    ]
