# Generated by Django 5.2.7 on 2025-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_flaggedcontent_moderationaction_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachment',
            name='forum_attach_post_idx',
        ),
        migrations.AddField(
            model_name='attachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when soft-deleted (for cleanup job)', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. False = deleted, True = active'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['post', 'is_active', 'display_order'], name='forum_attach_active_idx'),
        ),
    ]
