# Generated by Django 5.2.7 on 2025-11-05 21:39
# Split from 0006 to avoid field resolution issues

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_attachment_forum_attach_post_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['post', 'is_active', 'display_order'], name='forum_attach_active_idx'),
        ),
    ]
